# MediaMTX Configuration for OSCAR (High Density Optimization)
api: yes
apiAddress: :9997

# Protocols
# Disable unused protocols to save CPU/Memory
rtmp: no
hls: no
webrtc: no
srt: no

# Global Path Settings
paths:
  all:
    # Only establish connection to camera when someone is actually viewing it
    sourceOnDemand: yes
    # Increase buffer for high concurrency
    readBufferCount: 2048
